name: Build
on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Build binary for aarch64"
        required: true
        type: boolean

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup environment
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
        chmod 777 rustup-init.sh
        ./rustup-init.sh --help
        bash rustup-init.sh -y --default-toolchain nightly
        rustup target add aarch64-unknown-linux-musl --toolchain=nightly

        mkdir .zig
        cd .zig
        wget -O zig.tar.xz "https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2837+f38d7a92c.tar.xz"
        tar -xf zig.tar.xz
        rm zig.tar.xz
        mv * zig
        
    - name: Check compiler
      run: |
        # clang -v
        # clang-19 -v
        # llvm-ar-19 --version

    - name: Build
      run: |
        export PATH=$PATH:$PWD/.zig/zig
        export CC_aarch64_unknown_linux_musl="zig cc"
        export AR_aarch64_unknown_linux_musl="zig cc"
        # export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-Clink-self-contained=yes -Clinker=rust-lld"

        # rm /home/runner/.cargo/bin/rust-analyzer
        # rm /home/runner/.cargo/bin/rustfmt
        # rm /home/runner/.cargo/bin/cargo-fmt
        
        rustup update
        # export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=ld.lld-19
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="zig cc"
        export CC="zig cc"
        export CXX="zig cxx"
        CC="zig cc" cargo build --target aarch64-unknown-linux-musl --release

    - name: Check info
      run: |
        ls -ltrah
        ls -ltrah target/aarch64-unknown-linux-musl/release/
        tree

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: target/aarch64-unknown-linux-musl/release/ion
